#This is the jobs to be executed when a Release is created from workflows
name: Create Release

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Name of the release branch'
        required: true
      reason:
        description: 'Reason for release'
        required: true

env:
  GITHUB_TOKEN: ${{ github.token }}
  ORG_TOKEN: ${{ secrets.SVC_AWS_TRADING_DEV_CI_GPR_READ_ACCESS }}
  DOCKER_REGISTRY: "docker.pkg.github.com"

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Github User And Release Branch
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b releases/${{ github.event.inputs.branchName }}
          git push --set-upstream origin releases/${{ github.event.inputs.branchName }}

      - name: Release and tag version
        run: sbt "release with-defaults"

      - name: Create Release PR
        run: |
          hub pull-request -f -b main -m "Release ${{ github.event.inputs.branchName }}" -m "${{ github.event.inputs.reason }}"
